### ISSUE TITLE
SMD microswitch push button type

### ISSUE THREAD

**Issue by Silveriomrs** [gusmanb/micropicodrive#2]
Hello,
Your BOM doesn't include SMD microswitch push button.
I have some but none of the them match the thumb on the board. Legs are too short

Could you refer the kind of SMD mSwitch that you are using?
Thanks

**Comment by gusmanb** [comment]
These are standard 6x6mm SMD microswitches. Here you have an example: https://es.aliexpress.com/item/1005003115135192.html

**Comment by Silveriomrs** [comment]
Thank you, 
Definitively mine are not the right SMD for it.
![photo_2023-11-02_14-25-37](https://github.com/gusmanb/micropicodrive/assets/33696002/2208daad-8b51-4ded-ac7f-7aab170ee5a4)
![photo_2023-11-02_14-25-43](https://github.com/gusmanb/micropicodrive/assets/33696002/ad4f5ed1-f2a0-40f2-9f1d-c34614cdbc99)
