### ISSUE TITLE
Botton back doesn't work in some cases.

### ISSUE THREAD

**Issue by Silveriomrs** [gusmanb/micropicodrive#3]
Hi,
Exploring some sub-folder, reaching one empty sub-folder, the system cannot get back from it.

https://github.com/gusmanb/micropicodrive/assets/33696002/de9a0643-b0f7-4508-9eb6-2fc9ccfbf7ee

**Comment by gusmanb** [comment]
Will test it once I get a bit of spare time, right now I'm really busy until christmas.

**Comment by Silveriomrs** [comment]
Good afternoon!

Just in case my suspects are right... modifying my version of your firmware I got the candidate for the bug.
If you consider to modify yours, that is what I understood.

It join a infinite loop.
![2024-07-07_15-56](https://github.com/gusmanb/micropicodrive/assets/33696002/fdb33c07-6106-4668-8fe0-1b49ac16f26c)

Thanks

**Comment by gusmanb** [comment]
Ok, i have corrected it. Thanks.
