### ISSUE TITLE
the type initializer for "xamarin.tools.zip.native" threw an exception

### ISSUE THREAD

**Issue by gferluga** [gusmanb/micropicodrive#6]
When I try to open a ZIP file I'm getting this error message.

the type initializer for "xamarin.tools.zip.native" threw an exception

I'm running Windows 11 on a Silicon M2 MacBook:

Device name	W11Arm
Processor	Apple Part 000 r0p0   2.00 GHz
Installed RAM	4.00 GB
System type	64-bit operating system, ARM-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Pro
Version	23H2
Installed on	‎03/‎03/‎2024
OS build	22631.3235
Experience	Windows Feature Experience Pack 1000.22687.1000.0

Any idea? Thanks in advance...

**Comment by gusmanb** [comment]
Which version are you using? The compiled ones are only for x64, no ARM support. If you're compiling the code by yourself then I would recommend to run it in debug mode as the error should give you more information.

**Comment by gusmanb** [comment]
Sorry, can't help there, I have no ARM windows machines but I doubt it would work properly, linked libraries like the Zip one are x64 binaries and Windows in ARM uses an emulation layer to try to run native x64 apps and it's prone to fail.
