### ISSUE TITLE
The type initializer for "xamarin.tools.zip.native" threw an exception (Interl i9)

### ISSUE THREAD

**Issue by gferluga** [gusmanb/micropicodrive#8]
Hello, again...
This time the same issue "The type initializer for "xamarin.tools.zip.native" threw an exception" but on Intel i9 processor on Windows 11 on brand new HP Zbook machine.
Thanks...

**Comment by gusmanb** [comment]
Hi.

It seems that W11 + ZipLibSharp + Single File packaging screws up things.

Can you try this version?

[win-x64.zip](https://github.com/gusmanb/micropicodrive/files/15179366/win-x64.zip)

**Comment by gferluga** [comment]
Yes. It's working. Thanks!

**Comment by gferluga** [comment]
I'll try later on ARM Silicon Mac ;)-

**Comment by gferluga** [comment]
I confirm it's working on Windows 11 Arm from VmWare Fusion 17 on MacBook Silicon Arm M2. Hurray!!!
